/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wcr;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.System.exit;
import java.util.Date;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import wcr.reports.IndividualReport;

import wcr.reports.QuarterlyBF;
import wcr.reports.QuarterlyBFwithTotals;
import wcr.reports.ResignedWorkersRpt;

/**
 * @author 19950014 :: Reyden Yanoc
 */
public class MainForm extends javax.swing.JFrame {
    int wid=0,cid=0;
    boolean others = false;
    JDateChooser endDate = new JDateChooser();
    JDateChooser startDate = new JDateChooser();
    ButtonGroup quarterButtons = new ButtonGroup();
    Date day = new Date();
    String now = day.toString();
    public MainForm() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(".\\src\\ICONS\\Network.png"));//".\\src\\ICONS\\Network.png"
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        pack();
        
        hideEditButtons();
        fillTblWorkerInfo();
        arrangeTblWorkerInfo();
        jdc_dateRecorded.setDate(day);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_remarks = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_idnumber = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_mname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_designation = new javax.swing.JTextField();
        cbo_category = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jdc_dateRecorded = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ftxt_tulong = new javax.swing.JFormattedTextField();
        txt_locale = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_district = new javax.swing.JTextField();
        lbl_on = new javax.swing.JLabel();
        lbl_edit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_workerInfo = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_cancelEdit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.SystemColor.textHighlightText);
        setName("MainFrame"); // NOI18N
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("First name :");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Middle name :");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Last name:");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("ID Number :");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Designation :");
        jLabel5.setOpaque(true);

        txt_remarks.setColumns(20);
        txt_remarks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_remarks.setLineWrap(true);
        txt_remarks.setRows(5);
        txt_remarks.setTabSize(2);
        txt_remarks.setWrapStyleWord(true);
        txt_remarks.setBorder(null);
        jScrollPane2.setViewportView(txt_remarks);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Date :");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Category :");
        jLabel7.setOpaque(true);

        txt_idnumber.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_idnumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_idnumber.setPreferredSize(new java.awt.Dimension(6, 30));
        txt_idnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idnumberKeyTyped(evt);
            }
        });

        txt_fname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_fname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_fname.setPreferredSize(new java.awt.Dimension(6, 30));

        txt_mname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_mname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_mname.setPreferredSize(new java.awt.Dimension(6, 30));

        txt_lname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_lname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_lname.setPreferredSize(new java.awt.Dimension(6, 30));

        txt_designation.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_designation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_designation.setPreferredSize(new java.awt.Dimension(6, 30));

        cbo_category.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbo_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resigned", "Retired", "Early Retired", "Deceased", "Namatayan ng Asawa", "Namatayan ng Anak" }));
        cbo_category.setBorder(null);
        cbo_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_categoryActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Remarks :");
        jLabel8.setOpaque(true);

        jdc_dateRecorded.setForeground(new java.awt.Color(0, 204, 51));
        jdc_dateRecorded.setDateFormatString("MM/dd/yyyy");
        jdc_dateRecorded.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        //jdc_dateRecorded.getDateEditor().getUiComponent().setBackground(new java.awt.Color(226,239,254));
        jdc_dateRecorded.setPreferredSize(new java.awt.Dimension(91, 30));
        jdc_dateRecorded.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdc_dateRecordedKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Tulong na ibinigay :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Locale :");

        ftxt_tulong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        ftxt_tulong.setForeground(new java.awt.Color(204, 0, 0));
        ftxt_tulong.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        ftxt_tulong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxt_tulong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ftxt_tulong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxt_tulongKeyTyped(evt);
            }
        });

        txt_locale.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_locale.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("District:");

        txt_district.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_district.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        lbl_on.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_on.setForeground(new java.awt.Color(204, 0, 0));
        lbl_on.setText("ON");

        lbl_edit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_edit.setForeground(new java.awt.Color(204, 0, 0));
        lbl_edit.setText("edit mode");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jdc_dateRecorded, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_designation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxt_tulong))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_locale)
                            .addComponent(cbo_category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_district)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lbl_on))
                            .addComponent(lbl_edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jdc_dateRecorded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mname, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_designation, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbo_category, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_locale, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_district, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxt_tulong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(lbl_on)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_edit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jScrollPane1.setAutoscrolls(true);

        tbl_workerInfo.setFont(new java.awt.Font("Tahoma", 0, 16));
        tbl_workerInfo.getTableHeader().setFont(new java.awt.Font("Tahoma", 1, 16));
        tbl_workerInfo.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        tbl_workerInfo.getTableHeader().setBackground(new java.awt.Color(2,118,255));
        tbl_workerInfo.setSelectionBackground(new java.awt.Color(190,220,255));
        tbl_workerInfo.getTableHeader().setAutoscrolls(true);
        tbl_workerInfo.getTableHeader().setReorderingAllowed(false);
        //tbl_workerInfo.setAutoResizeMode(0);
        //tbl_workerInfo.setAutoscrolls(true);
        //tbl_workerInfo.setDragEnabled(false);
        //tbl_workerInfo.setAutoscrolls(true);
        tbl_workerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Number", "Name", "Designation", "Category", "Date", "Total BF", "Locale & District", "Remarks", "cati"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_workerInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbl_workerInfo.setFillsViewportHeight(true);
        tbl_workerInfo.setPreferredSize(new java.awt.Dimension(1500, 1000));
        tbl_workerInfo.setRowHeight(28);
        tbl_workerInfo.getColumnModel().getColumn(8).setWidth(1);
        tbl_workerInfo.setSelectionBackground(new java.awt.Color(247, 203, 203));
        tbl_workerInfo.setShowHorizontalLines(false);
        tbl_workerInfo.setFillsViewportHeight(true);
        tbl_workerInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_workerInfoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_workerInfoMouseReleased(evt);
            }
        });
        tbl_workerInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_workerInfoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_workerInfo);
        //jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        //jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(49, 103, 167));
        btn_search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/Zoom-icon.png"))); // NOI18N
        btn_search.setMnemonic('F');
        btn_search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btn_search.setMaximumSize(new java.awt.Dimension(79, 30));
        btn_search.setMinimumSize(new java.awt.Dimension(79, 30));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Enter ID number/Keyword :");
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(105, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(2, 118, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        btn_exit.setBackground(new java.awt.Color(49, 103, 167));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(204, 0, 51));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/Close-Program-icon.png"))); // NOI18N
        btn_exit.setMnemonic('X');
        btn_exit.setText("Exit");
        btn_exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(49, 103, 167));
        btn_print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/print-icon.png"))); // NOI18N
        btn_print.setMnemonic('P');
        btn_print.setText("Print");
        btn_print.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(49, 103, 167));
        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/Edit-icon.png"))); // NOI18N
        btn_edit.setMnemonic('E');
        btn_edit.setText("Edit");
        btn_edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(49, 103, 167));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/Save-icon.png"))); // NOI18N
        btn_save.setMnemonic('S');
        btn_save.setText("Save");
        btn_save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(49, 103, 167));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/cancel-Metro-icon.png"))); // NOI18N
        btn_cancel.setMnemonic('N');
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_cancelEdit.setBackground(new java.awt.Color(49, 103, 167));
        btn_cancelEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancelEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/cancel-Metro-icon.png"))); // NOI18N
        btn_cancelEdit.setMnemonic('N');
        btn_cancelEdit.setText("Cancel");
        btn_cancelEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 148, 148), 1, true));
        btn_cancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelEditActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(49, 103, 167));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/Update-icon.png"))); // NOI18N
        btn_update.setMnemonic('U');
        btn_update.setText("Update");
        btn_update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 148, 148), 1, true));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(49, 103, 167));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconified/Folder-Delete-icon.png"))); // NOI18N
        btn_delete.setMnemonic('D');
        btn_delete.setText("Delete");
        btn_delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 148, 148), 1, true));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btn_cancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel5.setBackground(new java.awt.Color(58, 99, 179));

        jLabel10.setBackground(new java.awt.Color(48, 90, 171));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EMPLOYEE BENEFIT FUND MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 714, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void hideEditButtons(){
        btn_cancelEdit.setVisible(false);
        btn_update.setVisible(false);
        btn_delete.setVisible(false);
        lbl_on.setVisible(false);
        lbl_edit.setVisible(false);
        btn_cancel.setEnabled(true);
        btn_save.setEnabled(true);
        btn_edit.setEnabled(true);
        btn_print.setEnabled(true);
        btn_exit.setEnabled(true);
        
    }
    private void showEditButtons(){
        btn_cancelEdit.setVisible(true);
        btn_update.setVisible(true);
        btn_delete.setVisible(true);
        lbl_on.setVisible(true);
        lbl_edit.setVisible(true);
        btn_cancel.setEnabled(false);
        btn_save.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_print.setEnabled(false);
        btn_exit.setEnabled(false);
        
    }
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_idnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idnumberKeyTyped
        char c = evt.getKeyChar();      
            if(!(Character.isDigit(c))|| txt_idnumber.getText().length() == 8){
                evt.consume();            
            }
    }//GEN-LAST:event_txt_idnumberKeyTyped

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
        if(jdc_dateRecorded.getDate()==null){
            JOptionPane.showMessageDialog(null, "Please choose a date.");
            jdc_dateRecorded.requestFocus();
            return;
        }if(getTxt_idnumber().getText().length()==0){
            JOptionPane.showMessageDialog(null, "ID Number is required field. ");
            txt_idnumber.requestFocus();
            return;
        }else if(getTxt_fname().getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Firstname is required field. ");
            txt_fname.requestFocus();
            return;
        }else if(getTxt_lname().getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Lastname is required field. ");
            txt_lname.requestFocus();
            return;
        }else if(getTxt_designation().getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Designation is required field. ");
            txt_designation.requestFocus();
            return;
        }else if(getTxt_locale().getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Locale is required field. ");
            txt_locale.requestFocus();
            return;
        }else if(getTxt_district().getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "District is required field. ");
            txt_district.requestFocus();  
            return;        
        }else if(getFtxt_tulong().getValue() == null){
            ftxt_tulong.setValue(0.0);
        }else if(getTxt_remarks().getText().isEmpty()){
            txt_remarks.setText(" ");
        }
        
        saveNewRecord();
       
        fillTblWorkerInfo();
        txt_idnumber.setText("");        
        txt_fname.setText("");
        txt_mname.setText("");
        txt_lname.setText("");
        txt_locale.setText("");
        txt_district.setText("");
        txt_designation.setText("");
        cbo_category.setSelectedIndex(1);
        ftxt_tulong.setValue(null);
        txt_remarks.setText("");
        txt_idnumber.requestFocus();
        cid = 0;
        wid = 0;
    }//GEN-LAST:event_btn_saveActionPerformed

    private void ftxt_tulongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxt_tulongKeyTyped
        char c = evt.getKeyChar();      
            if(!(Character.isDigit(c))){
                evt.consume();            
            }
    }//GEN-LAST:event_ftxt_tulongKeyTyped

    private void txt_idnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idnumberKeyReleased
        DataAccessForm da = new DataAccessForm();
        if(txt_idnumber.getText().length()==8){
                
                da.verifyId(getTxt_idnumber().getText());
                txt_fname.setText(da.f);
                txt_lname.setText(da.l);
                txt_mname.setText(da.m);                
            
            DefaultTableModel tableModel = (DefaultTableModel)tbl_workerInfo.getModel();
            tableModel.setRowCount(0);
            try{  
                tbl_workerInfo.setModel(da.searchKeyWord(getTxt_idnumber().getText(), tbl_workerInfo.getModel()));
                tbl_workerInfo.repaint(); 
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error in txt_idnumberKeyReleased "+e);
            }
        }
    }//GEN-LAST:event_txt_idnumberKeyReleased
     public void fillTblWorkerInfo(){
        
        DataAccessForm da=new DataAccessForm();
        try{  
            DefaultTableModel tableModel = (DefaultTableModel)tbl_workerInfo.getModel();
            tableModel.setRowCount(0);
            tbl_workerInfo.setModel(da.fillDataTable(tbl_workerInfo.getModel()));
            
            //FOR ALTERNATE TABLE ROW COLORS...>
            UIDefaults defaults = UIManager.getLookAndFeelDefaults();
            if (defaults.get("Table.alternateRowColor") == null)
                defaults.put("Table.alternateRowColor", new Color(223,224,225));
            //END FOR  ALTERNATE TABLE ROW COLORS..
            
            tbl_workerInfo.getColumnModel().getColumn(8).setWidth(0);
            tbl_workerInfo.repaint();
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in refreshPremiumTable "+e);
        }
    }
        public void setTableColumns(){
        TableColumn column;
        for(int i = 0; i < 8; i++){
            column = tbl_workerInfo.getColumnModel().getColumn(i);
            switch (i) {
                case 0:
                    column.setMinWidth(100);
                    column.setMaxWidth(100);
                    break;
                case 1:
                    column.setMinWidth(275);
                    column.setMaxWidth(275);
                    break;
                case 2:
                    column.setMinWidth(200);
                    column.setMaxWidth(200);
                    column.setResizable(true);
                    break;
                case 3:
                    column.setMinWidth(200);
                    column.setMaxWidth(200);
                    break;
                case 4:
                    column.setMinWidth(100);
                    column.setMaxWidth(100);
                    column.setResizable(true);
                    break;
                case 5:
                    column.setMinWidth(100);
                    column.setMaxWidth(100);
                    break;
                case 6:
                    column.setWidth(250);
                    column.setMinWidth(250);
                    column.setMaxWidth(250);
                    break;
                case 7:
                    column.setWidth(275);
                    column.setMinWidth(275);
                    column.setMaxWidth(275);
                    break;
                case 8:
                    
                    tbl_workerInfo.getColumnModel().getColumn(8).setMaxWidth(0);
                    tbl_workerInfo.getColumnModel().getColumn(8).setMinWidth(0);
                    tbl_workerInfo.getColumnModel().getColumn(8).setWidth(0);

                    break;
                default:
                    break;
            }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tbl_workerInfo.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbl_workerInfo.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tbl_workerInfo.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tbl_workerInfo.getColumnModel().getColumn(5).setCellRenderer(new RenderPrice());
    }
        public void unsetTableColumns(){
        TableColumn column;
        for(int i = 0; i < 8; i++){
            column = tbl_workerInfo.getColumnModel().getColumn(i);
            switch (i) {
                case 0:
                    column.setMinWidth(10);
                    break;
                case 1:
                    column.setMinWidth(10);
                    break;
                case 2:
                    column.setMinWidth(10);
                    break;
                case 3:
                    column.setMinWidth(10);
                    break;
                case 4:
                    column.setMinWidth(10);
                    break;
                case 5:
                    column.setMinWidth(10);
                    break;
                case 8:
                    tbl_workerInfo.getColumnModel().getColumn(8).setMaxWidth(0);
                    tbl_workerInfo.getColumnModel().getColumn(8).setMinWidth(0);
                    tbl_workerInfo.getColumnModel().getColumn(8).setWidth(0);
                    break;
                default:
                    break;
            }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tbl_workerInfo.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbl_workerInfo.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tbl_workerInfo.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tbl_workerInfo.getColumnModel().getColumn(5).setCellRenderer(new RenderPrice());
        
    }
    private void arrangeTblWorkerInfo(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tbl_workerInfo.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbl_workerInfo.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tbl_workerInfo.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tbl_workerInfo.getColumnModel().getColumn(5).setCellRenderer(new RenderPrice());
        if(this.getWidth() >= 1165){
            setTableColumns();
        }else{
            unsetTableColumns();
        }
    }
    private void jdc_dateRecordedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdc_dateRecordedKeyPressed
       
    }//GEN-LAST:event_jdc_dateRecordedKeyPressed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        
        showEditButtons();
        setFieldsEditable();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_cancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelEditActionPerformed
       
        cid = 0;
        wid = 0;
        hideEditButtons();
        clearFields();
    }//GEN-LAST:event_btn_cancelEditActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        //THIS IS TO MONITOR AND CHANGE SETTING EVERYTIME THE WINDOW IS 
        //MAXIMIZED OF MINIMIZED...
        if(this.getWidth() > 1165){
            setTableColumns();
        }else{
            unsetTableColumns();
        }
    }//GEN-LAST:event_formWindowStateChanged

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        DataAccessForm daf = new DataAccessForm();
        DefaultTableModel tableModel = (DefaultTableModel)tbl_workerInfo.getModel();
        tableModel.setRowCount(0);
        try{  
            tbl_workerInfo.setModel(daf.searchKeyWord(getTxt_search().getText(), tbl_workerInfo.getModel()));
            tbl_workerInfo.repaint(); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in refreshPremiumTable "+e);
        } 
    }//GEN-LAST:event_txt_searchKeyReleased

    private void tbl_workerInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_workerInfoKeyReleased
        fillValuesToFieldFromTable();
    }//GEN-LAST:event_tbl_workerInfoKeyReleased

    private void tbl_workerInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_workerInfoMouseClicked
        int ccnt = evt.getClickCount();
        if(ccnt==2){
            int row = tbl_workerInfo.getSelectedRow();
            String name = tbl_workerInfo.getValueAt(row, 0).toString() +"\nNAME: "+tbl_workerInfo.getValueAt(row, 1).toString();
            int ans = JOptionPane.showConfirmDialog(null, "Print this record? \n"+"ID NUMBER: "+name,"Please confirm",JOptionPane.OK_CANCEL_OPTION);
            
            if(ans == 0){
                IndividualReport ir = new IndividualReport();
                ir.idn = tbl_workerInfo.getValueAt(row, 0).toString();
                
                try{
                    JasperReportBuilder report = ir
                        .SummaryReportBuilder();
                        report.show(false);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"IndividualReport::option::"+e+ ir);
                }
            }
        }
        fillValuesToFieldFromTable();
    }//GEN-LAST:event_tbl_workerInfoMouseClicked

    private void tbl_workerInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_workerInfoMouseReleased
        fillValuesToFieldFromTable();
    }//GEN-LAST:event_tbl_workerInfoMouseReleased

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        cid = 0;
        wid = 0;
        btn_save.setEnabled(true);
        setFieldsEditable();
        clearFields();
        fillTblWorkerInfo();
        
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        if(cid == 0 && wid == 0){
            JOptionPane.showMessageDialog(null, "Please choose information by clicking on the table to edit.");
            return;
        }
        
        updateRecord();        
        fillTblWorkerInfo();
        jdc_dateRecorded.setDate(day);
        txt_idnumber.setText("");        
        txt_fname.setText("");
        txt_mname.setText("");
        txt_lname.setText("");
        txt_locale.setText("");
        txt_district.setText("");
        txt_designation.setText("");
        cbo_category.setSelectedIndex(1);
        ftxt_tulong.setValue(null);
        txt_remarks.setText("");
        txt_idnumber.requestFocus();
        cid = 0;
        wid = 0;
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if(cid>0){
            DataAccessForm da = new DataAccessForm();
            da.deleteData(cid, getTxt_idnumber().getText());
            clearFields();
            fillTblWorkerInfo();
            txt_idnumber.requestFocus();
            cid = 0;
            wid = 0;
        }else{
            JOptionPane.showMessageDialog(null, "Please choose information to delete from the table by clicking on it.");
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        
            Date d = new Date();
            int mon = d.getMonth()+1;
            int day = d.getDate();
            int yr = d.getYear()+1900;

            
            
            JPanel menuPanel = new JPanel();
            Dimension dmnsn = new Dimension(520, 500);
            Dimension smdmnsn = new Dimension(100,100);
            menuPanel.setPreferredSize(dmnsn);
            
            //ButtonGroup quarterButtons = new ButtonGroup(); 
            JRadioButton first4btn = new JRadioButton("1st Quarter");
            first4btn.setFont(new java.awt.Font("Tahoma", 0, 14));
            JRadioButton second4btn = new JRadioButton("2nd Quarter");
            second4btn.setFont(new java.awt.Font("Tahoma", 0, 14));
            JRadioButton third4btn = new JRadioButton("3rd Quarter");
            third4btn.setFont(new java.awt.Font("Tahoma", 0, 14));
            JRadioButton fourth4btn = new JRadioButton("4th Quarter");
            fourth4btn.setFont(new java.awt.Font("Tahoma", 0, 14));
            quarterButtons.add(first4btn);
            quarterButtons.add(second4btn);
            quarterButtons.add(third4btn);
            quarterButtons.add(fourth4btn);
                    
            menuPanel.setLayout(new GridLayout(13,0,0,5));
            
            JLabel qtrlbl = new JLabel("Quarterly Report - "+yr);            
            qtrlbl.setFont(new java.awt.Font("Tahoma", 1, 14));
            menuPanel.add(qtrlbl);            
            menuPanel.add(new JLabel(" "));
            menuPanel.add(new JSeparator());
            menuPanel.add(new JSeparator());
            menuPanel.add(first4btn);
            menuPanel.add(second4btn);
            menuPanel.add(third4btn);
            menuPanel.add(fourth4btn);
            
            
            ButtonGroup rpttypegrp = new ButtonGroup();
            JRadioButton bfbtn = new JRadioButton("Benefit Fund(BF)");
            bfbtn.setFont(new java.awt.Font("Tahoma", 0, 14));
            bfbtn.setSelected(true);
            JRadioButton reswbtn = new JRadioButton("Resigned workers");
            reswbtn.setFont(new java.awt.Font("Tahoma", 0, 14));
            rpttypegrp.add(bfbtn);
            rpttypegrp.add(reswbtn);
            
            JLabel rptType = new JLabel("Report Type");
            rptType.setFont(new java.awt.Font("Tahoma", 1, 16));
            menuPanel.add(rptType);
            menuPanel.add(new JLabel(""));
            menuPanel.add(new JSeparator());
            menuPanel.add(new JSeparator());
            menuPanel.add(bfbtn);
            menuPanel.add(reswbtn);
            
            JCheckBox otherDates = new JCheckBox("Check to print other dates");
            otherDates.setFont(new java.awt.Font("Tahoma", 1, 16));
            
            menuPanel.add(otherDates);    
            menuPanel.add(new JLabel(""));
            menuPanel.add(new JSeparator());
            menuPanel.add(new JSeparator());
            JLabel sdate = new JLabel("    Start date:");
            sdate.setFont(new java.awt.Font("Tahoma", 0, 16));
            menuPanel.add(sdate);

            startDate = new JDateChooser();
            startDate.setDateFormatString("MM/dd/yyyy");
            startDate.setFont(new java.awt.Font("Tahoma", 0, 16));
            startDate.setEnabled(false);
            menuPanel.add(startDate);

            endDate = new JDateChooser();
            endDate.setDateFormatString("MM/dd/yyyy");
            endDate.setFont(new java.awt.Font("Tahoma", 0, 16));
            endDate.setEnabled(false);        
            
            
            JLabel edate = new JLabel("    End date:");
            edate.setFont(new java.awt.Font("Tahoma", 0, 16));
            menuPanel.add(edate);
            menuPanel.add(endDate);
            JCheckBox bftotals = new JCheckBox("Check to include funds total");
            bftotals.setFont(new java.awt.Font("Tahoma", 1, 16));
            
            menuPanel.add(bftotals);
            menuPanel.add(new JLabel(""));
            menuPanel.add(new JSeparator());
            menuPanel.add(new JSeparator());
            
            ActionListener actionListener = new ActionListener() {
                        public void actionPerformed(ActionEvent actionEvent) {
                            AbstractButton abstractButton = (AbstractButton)actionEvent.getSource();
                            boolean selected = abstractButton.getModel().isSelected();
                                if(selected){
                                    endDate.setEnabled(true);
                                    startDate.setEnabled(true);
                                    others = true;  
                                    quarterButtons.clearSelection();
                                    
                                }else{
                                    others = false;
                                    endDate.setEnabled(false);
                                    startDate.setEnabled(false);
                                    if(mon <= 3){
                                        first4btn.setSelected(true);
                                    }else if(mon >= 4  && mon <= 6){
                                        second4btn.setSelected(true);
                                    }else if(mon >= 7 && mon <= 9){
                                        third4btn.setSelected(true);
                                    }else if(mon >= 10 && mon <= 12){
                                        fourth4btn.setSelected(true);
                                    }
                                }
                        }
            };
            ActionListener actionListener2 = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                            AbstractButton abstractButton = (AbstractButton)actionEvent.getSource();
                            boolean selected = abstractButton.getModel().isSelected();
                                if(selected){
                                    bftotals.setEnabled(true);
                                }else{
                                    bftotals.setEnabled(false);
                                }
                    }
            };
            ActionListener actionListener3 = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                            AbstractButton abstractButton = (AbstractButton)actionEvent.getSource();
                            boolean selected = abstractButton.getModel().isSelected();
                                if(selected){
                                        bftotals.setEnabled(false);
                                        bftotals.setSelected(false);
                                    }else{
                                        bftotals.setEnabled(true);
                                }
                    }  
            };
            ActionListener actionListener4 = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                            AbstractButton abstractButton = (AbstractButton)actionEvent.getSource();
                            boolean selected = abstractButton.getModel().isSelected();
                                if(selected){
                                        otherDates.setSelected(false);
                                        others = false;
                                        endDate.setEnabled(false);
                                        startDate.setEnabled(false);
                                    }else{
                                        //otherDates.setSelected(false);
                                }
                    }  
            };
            otherDates.addActionListener(actionListener);
            bfbtn.addActionListener(actionListener2);
            reswbtn.addActionListener(actionListener3);
            first4btn.addActionListener(actionListener4);
            second4btn.addActionListener(actionListener4);
            third4btn.addActionListener(actionListener4);
            fourth4btn.addActionListener(actionListener4);
            
            if(mon <= 3){
                first4btn.setSelected(true);
            }else if(mon >= 4  && mon <= 6){
                second4btn.setSelected(true);
            }else if(mon >= 7 && mon <= 9){
                third4btn.setSelected(true);
            }else if(mon >= 10 && mon <= 12){
                fourth4btn.setSelected(true);
            }
            
            ImageIcon Ico = new ImageIcon("C:\\ECDCS\\WCR\\src\\iconified\\print2-icon.png");
            int ans = JOptionPane.showConfirmDialog(null, menuPanel, "Print Menu", 
                    JOptionPane.CANCEL_OPTION, JOptionPane.OK_CANCEL_OPTION, Ico);
            
            
            
            
            if(ans==0){
                int startmon = 0;
                int endmon = 0;
                
                if(quarterButtons.isSelected(first4btn.getModel())){
                        if(first4btn.isSelected()){
                            startmon = 1;
                            endmon = 3;
                        }
                    }else if(quarterButtons.isSelected(second4btn.getModel())){
                        if(second4btn.isSelected()){
                            startmon = 4;
                            endmon = 6;
                        }
                    }else if(quarterButtons.isSelected(third4btn.getModel())){
                        if(third4btn.isSelected()){
                            startmon = 7;
                            endmon = 9;
                        }
                    }else if(quarterButtons.isSelected(fourth4btn.getModel())){
                            startmon = 10;
                            endmon = 12;
                    }
                
                if(others==true){
                    
                       if(bfbtn.isSelected()==true){
                            
                            if(!(bftotals.isSelected())){
                                
                                QuarterlyBF sbf = new QuarterlyBF();
                                sbf.syear = startDate.getJCalendar().getYearChooser().getYear();
                                sbf.eyear = endDate.getJCalendar().getYearChooser().getYear();
                                sbf.smon = startDate.getJCalendar().getMonthChooser().getMonth()+1;
                                sbf.emon = endDate.getJCalendar().getMonthChooser().getMonth()+1;
                                
                                try{
                                JasperReportBuilder report = sbf
                                    .SummaryReportBuilder();
                                    report.show(false);
                                }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"SummaryBF::option::"+e);
                                }
                            }else if(bftotals.isSelected()){
                                
                                
                                QuarterlyBFwithTotals qbt = new QuarterlyBFwithTotals();
                                qbt.syear = startDate.getJCalendar().getYearChooser().getYear();
                                qbt.eyear = endDate.getJCalendar().getYearChooser().getYear();
                                qbt.smon = startDate.getJCalendar().getMonthChooser().getMonth()+1;
                                qbt.emon = endDate.getJCalendar().getMonthChooser().getMonth()+1;
                                
                                try{
                                JasperReportBuilder report = qbt
                                    .SummaryReportBuilder();
                                    report.show(false);
                                }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"SummaryBF::option::"+e);
                                }
                            }
                        }else if(reswbtn.isSelected()==true){
                            ResignedWorkersRpt rwr = new ResignedWorkersRpt();
                            rwr.syear = startDate.getJCalendar().getYearChooser().getYear();
                            rwr.eyear = endDate.getJCalendar().getYearChooser().getYear();
                            rwr.smon = startDate.getJCalendar().getMonthChooser().getMonth()+1;
                            rwr.emon = endDate.getJCalendar().getMonthChooser().getMonth()+1;
                            try{
                                JasperReportBuilder report = rwr                            
                                .ResignedRptBuilder();
                                report.show(false);
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"SummaryBF::option::"+e);
                            }
                        }
                        
                }else if(others==false){
                      
                        if(bfbtn.isSelected()==true){
                            
                            if(!(bftotals.isSelected())){
                                
                                QuarterlyBF sbf = new QuarterlyBF();
                                sbf.syear = yr;
                                sbf.eyear = yr;
                                sbf.smon = startmon;
                                sbf.emon = endmon;
                                /*JOptionPane.showMessageDialog(null,"syear = "+ yr +"  eyear = "+ yr +" "
                                        + "smon = "+ startmon +" emon = "+ endmon);
                                */
                                try{
                                JasperReportBuilder report = sbf
                                    .SummaryReportBuilder();
                                    report.show(false);
                                }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"SummaryBF::option::"+e);
                                }
                            }else if(bftotals.isSelected()){
                                QuarterlyBFwithTotals qbt = new QuarterlyBFwithTotals();
                                qbt.syear = yr;
                                qbt.eyear = yr;
                                qbt.smon = startmon;
                                qbt.emon = endmon;
                                //JOptionPane.showConfirmDialog(null,"Warning this page is not yet final.");
                                
                                try{
                                    JasperReportBuilder report = qbt
                                        .SummaryReportBuilder();
                                        report.show(false);
                                }catch(Exception e){
                                        JOptionPane.showMessageDialog(null,"SummaryBF::option::"+e);
                                }
                            }
                        }else if(reswbtn.isSelected()==true){
                            ResignedWorkersRpt rwr = new ResignedWorkersRpt(); 
                            rwr.syear = yr;
                            rwr.eyear = yr;
                            rwr.smon = startmon;
                            rwr.emon = endmon;
                            try{
                                JasperReportBuilder report = rwr                            
                                .ResignedRptBuilder();
                                report.show(false);
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"SummaryBF::option::"+e);
                            }
                        }
                    }
                 
            }else{
                
            }
            
            others=false;
            
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        txt_search.requestFocus();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void cbo_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_categoryActionPerformed

    private void fillValuesToFieldFromTable(){
        try{
        int row = tbl_workerInfo.getSelectedRow();
        String id = tbl_workerInfo.getModel().getValueAt(row, 0).toString();
        DataAccessForm daf = new DataAccessForm();
        Object data[];
        data = daf.workerData(id);
        txt_idnumber.setText(id);        
        txt_fname.setText(data[1].toString());
        txt_mname.setText(data[2].toString());
        txt_lname.setText(data[3].toString());
        txt_locale.setText(data[4].toString());
        txt_district.setText(data[5].toString());
        txt_designation.setText(tbl_workerInfo.getModel().getValueAt(row,2).toString());
        cbo_category.setSelectedItem(tbl_workerInfo.getModel().getValueAt(row, 3).toString());
        ftxt_tulong.setValue(tbl_workerInfo.getModel().getValueAt(row, 5));
        txt_remarks.setText(tbl_workerInfo.getModel().getValueAt(row, 7).toString());
        ((JTextField)jdc_dateRecorded.getDateEditor().getUiComponent()).
                setText(tbl_workerInfo.getModel().getValueAt(row, 4).toString());
        wid = Integer.parseInt(data[0].toString());
        cid = Integer.parseInt(tbl_workerInfo.getModel().getValueAt(row, 8).toString());
        btn_save.setEnabled(false);
        if(btn_edit.isEnabled())
            setFieldsNotEditable();
        }catch(Exception e){
            
        }
    }
     private void setFieldsNotEditable(){
      
        txt_idnumber.setEditable(false);
        txt_idnumber.setDisabledTextColor(Color.BLACK);
        txt_fname.setEditable(false);
        txt_fname.setDisabledTextColor(Color.BLACK);
        txt_mname.setEditable(false);
        txt_mname.setDisabledTextColor(Color.BLACK);
        txt_lname.setEditable(false);
        txt_lname.setDisabledTextColor(Color.BLACK);
        txt_locale.setEditable(false);
        txt_locale.setDisabledTextColor(Color.BLACK);
        txt_district.setEditable(false);
        txt_district.setDisabledTextColor(Color.BLACK);
        txt_designation.setEditable(false);
        txt_designation.setDisabledTextColor(Color.BLACK);     
        ftxt_tulong.setEditable(false);
        ftxt_tulong.setDisabledTextColor(Color.RED);
        txt_remarks.setEditable(false);
        txt_remarks.setDisabledTextColor(Color.BLACK);
               
    }
    private void setFieldsEditable(){
      
        txt_idnumber.setEditable(true);
        txt_fname.setEditable(true);
        txt_mname.setEditable(true);
        txt_lname.setEditable(true);
        txt_locale.setEditable(true);
        txt_district.setEditable(true);
        txt_designation.setEditable(true);     
        ftxt_tulong.setEditable(true);
        txt_remarks.setEditable(true);
        
    }
    private void clearFields(){
        txt_idnumber.setText("");        
        txt_fname.setText("");
        txt_mname.setText("");
        txt_lname.setText("");
        txt_locale.setText("");
        txt_district.setText("");
        txt_designation.setText("");
        cbo_category.setSelectedIndex(1);
        ftxt_tulong.setValue(null);
        txt_remarks.setText("");
        ((JTextField)jdc_dateRecorded.getDateEditor().getUiComponent()).
                setText(null);
        jdc_dateRecorded.setDate(day);
    }
    
    public void saveNewRecord(){
        try{
        DataAccessForm daf = new DataAccessForm();
        daf.insertNewRecord(getTxt_idnumber().getText(),
                            getTxt_lname().getText(), getTxt_fname().getText(),
                            getTxt_mname().getText(), getTxt_designation().getText(), 
                            cbo_category.getSelectedItem().toString(),
                            jdc_dateRecorded.getJCalendar().getDayChooser().getDay(), 
                            jdc_dateRecorded.getJCalendar().getMonthChooser().getMonth()+1, 
                            jdc_dateRecorded.getJCalendar().getYearChooser().getYear(),
                            getTxt_locale().getText(),getTxt_district().getText(),
                            Double.parseDouble(getFtxt_tulong().getValue().toString()),
                            getTxt_remarks().getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in saveNewRecord  :: "+e);
            return;
        }
                                                                                
    }
    public void updateRecord(){
        try{
        DataAccessForm daf = new DataAccessForm();
        daf.updateRecord(wid,getTxt_idnumber().getText(),
                            getTxt_lname().getText(), getTxt_fname().getText(),
                            getTxt_mname().getText(), getTxt_designation().getText(), 
                            cbo_category.getSelectedItem().toString(),
                            jdc_dateRecorded.getJCalendar().getDayChooser().getDay(), 
                            jdc_dateRecorded.getJCalendar().getMonthChooser().getMonth()+1, 
                            jdc_dateRecorded.getJCalendar().getYearChooser().getYear(),
                            getTxt_locale().getText(),getTxt_district().getText(),
                            Double.parseDouble(getFtxt_tulong().getValue().toString()),
                            getTxt_remarks().getText(),cid);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in updateRecord :: "+e);
            return;
        }
    }
    public JDateChooser getJdc_dateRecorded() {
        return jdc_dateRecorded;
    }

    public void setJdc_dateRecorded(JDateChooser jdc_dateRecorded) {
        this.jdc_dateRecorded = jdc_dateRecorded;
    }

    public JTextField getTxt_designation() {
        return txt_designation;
    }

    public void setTxt_designation(JTextField txt_designation) {
        this.txt_designation = txt_designation;
    }

    public JTextField getTxt_fname() {
        return txt_fname;
    }

    public void setTxt_fname(JTextField txt_fname) {
        this.txt_fname = txt_fname;
    }

    public JTextField getTxt_idnumber() {
        return txt_idnumber;
    }

    public void setTxt_idnumber(JTextField txt_idnumber) {
        this.txt_idnumber = txt_idnumber;
    }

    public JTextField getTxt_lname() {
        return txt_lname;
    }

    public void setTxt_lname(JTextField txt_lname) {
        this.txt_lname = txt_lname;
    }

    public JTextField getTxt_mname() {
        return txt_mname;
    }

    public void setTxt_mname(JTextField txt_mname) {
        this.txt_mname = txt_mname;
    }

    public JTextArea getTxt_remarks() {
        return txt_remarks;
    }

    public void setTxt_remarks(JTextArea txt_remarks) {
        this.txt_remarks = txt_remarks;
    }

    public JTextField getTxt_search() {
        return txt_search;
    }

    public void setTxt_search(JTextField txt_search) {
        this.txt_search = txt_search;
    }

    public JComboBox<String> getCbo_category() {
        return cbo_category;
    }

    public void setCbo_category(JComboBox<String> cbo_category) {
        this.cbo_category = cbo_category;
    }

    public JFormattedTextField getFtxt_tulong() {
        return ftxt_tulong;
    }

    public void setFtxt_tulong(JFormattedTextField ftxt_tulong) {
        this.ftxt_tulong = ftxt_tulong;
    }

    public JTextField getTxt_district() {
        return txt_district;
    }

    public void setTxt_district(JTextField txt_district) {
        this.txt_district = txt_district;
    }

    public JTextField getTxt_locale() {
        return txt_locale;
    }

    public void setTxt_locale(JTextField txt_locale) {
        this.txt_locale = txt_locale;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //UIManager.put("this.activeTitleBackground", Color.MAGENTA);
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cancelEdit;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbo_category;
    private javax.swing.JFormattedTextField ftxt_tulong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdc_dateRecorded;
    private javax.swing.JLabel lbl_edit;
    private javax.swing.JLabel lbl_on;
    private javax.swing.JTable tbl_workerInfo;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_district;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_idnumber;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_locale;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JTextArea txt_remarks;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
